IYogaKoo/Controllers/YogaUserDetailController.cs
using Commons.Helper;
using IYogaKoo.Client;
using IYogaKoo.Entity;
using IYogaKoo.ViewModel;
using IYogaKoo.ViewModel.Commons.Enums;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace IYogaKoo.Controllers
{
    public class YogaUserDetailController : Controller
    {
        //
        // GET: /YogaUserDetail/
        ///获取用户信息cookie 
        BasicInfo user = Commons.Helper.Login.GetCurrentUser();
        YogisModelsServiceClient client;
        YogaUserServiceClient clientUser;
        tMessageServiceClient clientMsg;
        tWriteLogServiceClient logClient;
        YogaPictureServiceClient clientPic;
        YogaUserDetailServiceClient userDetclient;
        YogaDicItemServiceClient dicclient;
        FollowServiceClient clientfollow;
        LevelOrderServiceClient levelorderclient;
        /// <summary>
        /// 我感兴趣的活动
        /// </summary>
        InterestServiceClient interclient;
        /// <summary>
        /// 我报名的活动
        /// </summary>
        OrderServiceClient orderclient;
        ClassServiceClient classclient;
        CentersServiceClient cenclient;
        method method;
        tZanModelsServiceClient zanclient;
        tLearingServiceClient learnclient;
        public YogaUserDetailController()
        {
            ViewBag.user = user;
            client = new YogisModelsServiceClient();
            clientUser = new YogaUserServiceClient();
            clientMsg = new tMessageServiceClient();
            logClient = new tWriteLogServiceClient();
            clientPic = new YogaPictureServiceClient();
            userDetclient = new YogaUserDetailServiceClient();
            dicclient = new YogaDicItemServiceClient();
            clientfollow = new FollowServiceClient();
            interclient = new InterestServiceClient();
            orderclient = new OrderServiceClient();
            classclient = new ClassServiceClient();
            method = new method();
            zanclient = new tZanModelsServiceClient();
            levelorderclient = new LevelOrderServiceClient();
            cenclient = new CentersServiceClient();
            learnclient = new tLearingServiceClient();
            #region 登录者的级别
            if (user.UserType == 0)
            {
                ViewYogaUserDetail temp = new ViewYogaUserDetail();
                temp = userDetclient.GetYogaUserDetailById(user.Uid);
                if (temp != null)
                    ViewBag.level = temp.Ulevel;
            }
            else
            {
                ViewYogisModels vyogism = new ViewYogisModels();
                vyogism = client.GetYogisModelsById(user.Uid);
                if (vyogism != null)
                    ViewBag.level = vyogism.YogisLevel;
            }
            #endregion
            #region  站内信-信息数量

            int tinstatcount = 0;
            int follcount = 0;
            int zancount = 0;
            int msgcount = 0;

            method.InstationInfo(user.Uid, out   tinstatcount, out   follcount, out   zancount, out   msgcount);

            ViewBag.tinstatcount = tinstatcount;
            ViewBag.follcount = follcount;
            ViewBag.zancount = zancount;
            ViewBag.msgcount = msgcount;
            ViewBag.AllCount = tinstatcount + follcount + zancount + msgcount;
            #endregion
        }
        //
        // GET: /Mechanism/

        public ActionResult Index(int page = 1)
        {

            //派别
            int typeid = 0;
            if (!string.IsNullOrEmpty(Request.Form["typeid"]))
            {
                typeid = Convert.ToInt32(Request.Form["typeid"]);
            }
            int level = 0;
            //瑜伽类别
            if (!string.IsNullOrEmpty(Request.Form["levelid"]))
            {
                level = Convert.ToInt32(Request.Form["levelid"]);
            }

            //国家
            int CountryID = 0;
            if (!string.IsNullOrEmpty(Request.Form["hidCountryID"]))
            {
                CountryID = Convert.ToInt32(Request.Form["hidCountryID"]);
            }

            //省份
            int ProvinceID = 0;
            if (!string.IsNullOrEmpty(Request.Form["hidProvinceID"]))
            {
                ProvinceID = Convert.ToInt32(Request.Form["hidProvinceID"]);
            }

            //城市
            int CityID = 0;
            if (!string.IsNullOrEmpty(Request.Form["hidCityID"]))
            {
                CityID = Convert.ToInt32(Request.Form["hidCityID"]);
            }
            //地区
            int DistrictID = 0;
            if (!string.IsNullOrEmpty(Request.Form["hidDistrictID"]))
            {
                DistrictID = Convert.ToInt32(Request.Form["hidDistrictID"]);
            }

            string name = string.Empty;

            List<ViewYogaUserDetail> list = new List<ViewYogaUserDetail>();
            int count = 0;
            int pagesize = 12;
            List<ViewYogaUser> listuser = clientUser.BackGetPageList(0);

            string idsUId = string.Join(",",listuser.Select(a=>a.Uid));

            list = userDetclient.GetYogaUserList("", DistrictID, CityID, ProvinceID, CountryID, typeid, level, 2, out count);

            List<ViewUserDetailGroup> users = new List<ViewUserDetailGroup>();
            ViewUserDetailGroup user = new ViewUserDetailGroup();
            ViewYogaDicItem dicitem = null;
            foreach (ViewYogaUserDetail c in list)
            {
                foreach (var ik in idsUId.Split(','))
                {
                    if (c.UID == Convert.ToInt32(ik))
                    {
                        #region

                        c.DisplayImg = CommonInfo.GetDisplayImg(c.DisplayImg);
                        user = new ViewUserDetailGroup();
                        user.VDetailsList = c;
                        //派别
                        string typename = string.Empty;
                        if (c.YogaTypeid != null)
                        {
                            string[] arrtypeid = c.YogaTypeid.Split(',');

                            for (int i = 0; i < arrtypeid.Length; i++)
                            {
                                if (!String.IsNullOrEmpty(arrtypeid[i]))
                                {
                                    int result = 0;
                                    if (Int32.TryParse(arrtypeid[i], out result))
                                    {
                                        dicitem = dicclient.GetYogaDicItemById(result);
                                        if (dicitem != null)
                                        {
                                            typename += dicitem.ItemName + ",";
                                        }
                                    }
                                }
                            }
                            if (!String.IsNullOrEmpty(typename))
                            {
                                typename = typename.Substring(0, typename.Length - 1);
                            }
                        }
                        user.usertype = typename;

                        //昵称
                        ViewYogaUser u = clientUser.GetYogaUserById(c.UID);
                        user.VyList = u;
                        //粉丝
                        user.FollowCount = clientfollow.GetFollowByCount(c.UID);
                        users.Add(user);
                        #endregion
                    }
                
                }
               
            }
            count = users.Count();
            users = users.
                OrderByDescending(x => x.FollowCount).
                OrderByDescending(x => !string.IsNullOrEmpty(x.VDetailsList.DisplayImg))
                .Skip((page - 1) * pagesize).Take(pagesize).ToList();
           
             Webdiyer.WebControls.Mvc.PagedList<ViewUserDetailGroup> pagelist = new Webdiyer.WebControls.Mvc.PagedList<ViewUserDetailGroup>(users, page, pagesize, count);
            if (Request.IsAjaxRequest())
            {
                return PartialView("IndexList", pagelist);
            }
            return View(pagelist);
        }

        //
        // GET: /YogaUserDetail/Details/5

        public ActionResult Details(int id, int page = 1)
        {
            try
            {
                ///Follow iType
                ViewBag.UserType = 0;
                ViewBag.id = id;
                int strUid = 0;
                int iLoginID = user.Uid;//登录用户ID
                ViewBag.iLoginID = user.Uid;

                #region 习练者专页 基本信息


                ViewYogaUserDetail temp = new ViewYogaUserDetail();

                temp = userDetclient.GetYogaUserDetailById(id);

                #region 习练者基本信息
                strUid = temp.UID;
                ViewBag.strUid = temp.UID;
                ///位置
                string strCountryID = "";
                string strProvinceID = "";
                string strCityID = "";
                string strDistrictID = "";
                if (temp.CountryID != null && temp.CountryID != 0)
                {
                    strCountryID = GetItemName(temp.CountryID.Value) + "·";
                }
                if (temp.ProvinceID != null && temp.ProvinceID != 0)
                {
                    strProvinceID = GetItemName(temp.ProvinceID.Value) + "·";
                }
                if (temp.CityID != null && temp.CityID != 0)
                {
                    strCityID = GetItemName(temp.CityID.Value) + "·";
                }
                if (temp.DistrictID != null && temp.DistrictID != 0)
                {
                    strDistrictID = GetItemName(temp.DistrictID.Value);
                }

                ViewBag.AddRessName = strCountryID + strProvinceID + strCityID + strDistrictID;
                ///流派

IYogaKoo/Views/YogaUserDetail/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model Webdiyer.WebControls.Mvc.PagedList<IYogaKoo.ViewModel.ViewUserDetailGroup>
@{
    ViewBag.Title = "习练者";
}
@using (Html.BeginForm("Index", "YogaUserDetail", new { id = "" }, FormMethod.Post, new { id = "searchForm" }))
{
    <div class="lb_login_idnex_top" style="border-top:5px solid #65C3A5">
        <div class="lb_login_idnex_top_index">
            <b>您所在位置：</b><span style="font-weight:bold">瑜伽习练者</span>
        </div>
    </div>
    <div id="anchorTag" class="lb_lb_School_zhuti">
        <b>@*瑜伽练习者：*@   &nbsp;</b>
        <ul>
            <li tid="0" class="on">全部</li>
            <li tid="1">基础习练者</li>
            <li tid="2">初级习练者</li>
            <li tid="3">中级习练者</li>
            <li tid="4">高级习练者</li>
        </ul>
        <input type="hidden" id="levelid" name="levelid" />
    </div>
<div class="lb_lb_School_liupaii">
    <b>瑜伽流派：</b>
    <ul>
        <li tid="0" class="on">全部</li>
        <li tid="115">哈他</li>
        <li tid="118">艾扬格</li>
        <li tid="119">阿斯汤加</li>
        <li tid="101">流瑜伽</li>
        <li tid="120">阴瑜伽</li>
    </ul>
    <input type="hidden" id="typeid" name="typeid" />
</div>
<div class="lb_lb_School_diqu">
    <b class="b">所在地区：</b>
    <select id="ddlCountryID" name="ddlCountryID"></select>
    <input type="hidden" name="hidCountryID" id="hidCountryID" />
    <select id="ddlProvinceID" name="ddlProvinceID">
        <option value="0">请选择省份</option>
    </select>
    <input type="hidden" name="hidProvinceID" id="hidProvinceID" />
    <select id="ddlCityID" name="ddlCityID" >
        <option value="0">请选择城市</option>
    </select>
    <input type="hidden" name="hidCityID" id="hidCityID" />
    <select id="ddlDistrictID" name="ddlDistrictID" >
        <option value="0">请选择城区</option>
    </select>
    <input type="hidden" name="hidDistrictID" id="hidDistrictID" />
</div>
} 

    <div class="lb_School_index_index" style="width:1210px">
        <div class="lb_School_index_index_lln">
            <div style="display:block" id="Content">
                @Html.Partial("IndexList", Model)
            </div>
        </div>
    </div>
        @section styles
{
            <link type="text/css" href="/Content/Front/css/pagerstyles.css" rel="stylesheet" />
           
        }
        @section scripts {
            <script type="text/javascript">
                $(function () {
                    $(".lb_lb_School_zhuti ul li").click(function () {
                        var typeid = $(this).attr("tid");
                        $("#levelid").val(typeid);
                        $(this).addClass("on").siblings().removeClass("on");
                        $("#searchForm").submit();
                    });
                    $(".lb_lb_School_liupaii ul li").click(function () {
                        var typeid = $(this).attr("tid");
                        $("#typeid").val(typeid);
                        $(this).addClass("on").siblings().removeClass("on");
                        $("#searchForm").submit();
                    });

                    $.ajax({
                        url: '/Login/GetCountryInfo?t=' + Math.random(),
                        type: 'post',
                        datatype: 'json',
                        success: function (data) {
                            $("#ddlCountryID").append("<option value='0' selected='selected'>请选择国家</option>");
                            for (var i = 0; i < data.length; i++) {
                                $("#ddlCountryID").append("<option value='" + data[i].ID + "'   >" + data[i].ItemName + "</option>");
                            };
                        }
                    });
                   
                });

                // 国家事件
                $('#ddlCountryID').change(function () {
                    var strGuoJia = $(this).val();
                    $("#hidCountryID").val(strGuoJia);
                    //加载省
                    $.ajax({
                        url: '/Login/GetAreaInfo?id=' + strGuoJia,
                        type: 'post',
                        datatype: 'json',
                        success: function (data) {
                            $("#ddlProvinceID").html("<option value='0'>请选择</option>");
                            $("#ddlCityID").html("<option value='0'>请选择</option>");
                            $("#ddlDistrictID").html("<option value='0'>请选择</option>");
                            for (var i = 0; i < data.length; i++) {

                                $("#ddlProvinceID").append("<option value='" + data[i].ID + "'>" + data[i].ItemName + "</option>");

                            };
                        }
                    });
                    $("#searchForm").submit();
                });
                //省事件
                $("#ddlProvinceID").change(function () {
                    var strSheng = $(this).val();
                    $("#hidProvinceID").val(strSheng);
                    //加载市
                    $.ajax({
                        url: '/Login/GetAreaInfo?id=' + strSheng,
                        type: 'post',
                        datatype: 'json',
                        success: function (data) {
                            $("#ddlCityID").html("<option value='0'>请选择</option>");
                            //$("#ddlDistrictID").html("<option value='0'>请选择</option>");
                            for (var i = 0; i < data.length; i++) {

                                $("#ddlCityID").append("<option value='" + data[i].ID + "'>" + data[i].ItemName + "</option>");

                            };
                        }
                    });
                    $("#searchForm").submit();
                });
                //城市事件
                $("#ddlCityID").change(function () {
                    var strShi = $(this).val();
                    $("#hidCityID").val(strShi);
                    //加载城区
                    $.ajax({
                        url: '/Login/GetAreaInfo?id=' + strShi,
                        type: 'post',
                        datatype: 'json',
                        success: function (data) {
                            //$("#ddlDistrictID").append("<option value='0'>请选择</option>");
                            for (var i = 0; i < data.length; i++) {

                                $("#ddlDistrictID").append("<option value='" + data[i].ID + "'>" + data[i].ItemName + "</option>");

                            };
                        }
                    });
                    $("#searchForm").submit();
                });
                //城市事件
                $("#ddlDistrictID").change(function () {
                    var strShi = $(this).val(); console.log(strShi);
                    $("#hidDistrictID").val(strShi);
                    $("#searchForm").submit();
                });
                function pagelocation() { 
                    $("html,body").stop(true); $("html,body").animate({ scrollTop: $("#anchorTag").offset().top }, 100);
                }
            </script>

            <script src=@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")></script>
            @{Html.RegisterMvcPagerScriptResource();}
        }

IYogaKoo/Views/YogaUserDetail/IndexList.cshtml
@using Webdiyer.WebControls.Mvc
@model Webdiyer.WebControls.Mvc.PagedList<IYogaKoo.ViewModel.ViewUserDetailGroup>
@{
    Layout = null;
}
@foreach (var item in Model)
{
    <div class="lb_teacher_div2">
        <div class="lb_teacher_div_top" style="text-align:center">
            @{
    string title = string.Empty;
    if (item.VyList != null && item.VyList.NickName != null)
    {
        title = item.VyList.NickName;
    }
            }
            <a href="/YogaUserDetail/Details/@item.VDetailsList.UID"  title="@title">

                <img  src="@(!String.IsNullOrEmpty(item.VDetailsList.DisplayImg) ? Commons.Helper.CommonInfo.GetDisplayImg(item.VDetailsList.DisplayImg) : "/Content/Front/images/defaultImg.png")" onerror="javascript: this.src = '/Content/Front/images/defaultImg.png'" width="278"   height="230">
    </a>
        </div>
        <div class="lb_teacher_div_bottom">
            <div class="lb_teacher_div_bottom_top">
                <b>  @{
    if (item.VyList != null && item.VyList.NickName != null)
    {
        string temprealname = item.VyList.NickName.Replace("(", "（");
        int khindex = temprealname.IndexOf("（");
        if (khindex > 8)
        {
            @(temprealname.Substring(0, khindex))
                    <br />
            int khindex2 = temprealname.Length - khindex;

            @(temprealname.Substring(temprealname.IndexOf("（") + 1, khindex2 - 2))
        }
        else
        {
            @temprealname
       }
    }

                } </b>
                <span style="float:right; margin-right:5px;">@item.FollowCount</span><a></a>
            </div>
            <div class="lb_teacher_div_bottom_top" style="display:none;">
                <p>@{
    if (item.usertype != null)
    {
        if (item.usertype.Length > 5)
        {
           @(item.usertype.Substring(0, 5))
        }
        else
        {
            @item.usertype
        }
    }

                }  </p>
                
            </div>
            <div class="lb_teacher_div_bottom_top2">
                <p word="@item.VDetailsList.GudWords">
                    @{
    if (item.VDetailsList.GudWords != null)
    {
        if (item.VDetailsList.GudWords.Length > 31)
        {
            @(item.VDetailsList.GudWords.Substring(0, 31)+"..")
        }
        else
        {
            @item.VDetailsList.GudWords
        }
    }
                    }


                </p>
            </div>
        </div>
    </div>
   
}
<script language="javascript">
    $(function () {
        //悬浮
        var xuindex;
        $(".lb_teacher_div_bottom_top2 p").hover(function () {
            var pval = $(this).attr("word");
            xuindex = layer.tips(pval, this, { tips: [1, '#65c3a5'] }); console.log(index);
        }, function () {
            layer.close(xuindex);
        });
    });
</script>
<div style="clear:both"></div>
<div style="display:block; width:100%">
    <div class="text-center" style="" id="menepager">
        @Ajax.Pager(Model, new PagerOptions
{
    PageIndexParameterName = "page",
    PrevPageText = "上一页",
    NextPageText = "下一页",
    FirstPageText = "首页",
    LastPageText = "尾页",  
    ContainerTagName = "ul",
    CssClass = "menepager",
    CurrentPagerItemTemplate = "<li class=\"active\"><a  >{0}</a></li>",
    DisabledPagerItemTemplate = "<li class=\"disabled\"><a>{0}</a></li>",
    PagerItemTemplate = "<li>{0}</li>"
}, new MvcAjaxOptions { UpdateTargetId = "Content", HttpMethod = "Post",  OnComplete = "pagelocation", DataFormId = "searchForm" })
    </div>
</div>

IYogaKoo/Views/YogaUserDetail/LevelAuthentication.cshtml
@model IYogaKoo.ViewModel.ViewYogaUserDetail

@{
    ViewBag.Title = "LevelAuthentication";
    Layout = "~/Views/Shared/_LayoutSetUp.cshtml";
}
<style>
    #lb_casuh label {
    line-height:25px
    }
</style>
<div class="lb_pd_index">
    <p style="margin-left:45px!important">自我级别评定&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        @Html.LabelFor(model => model.Ulevel)：
        @{
            if (Model.Ulevel == null || Model.Ulevel == 0)
            {
                @:基础习练者
                }

            if (Model.Ulevel == 1)
            {
                @:初级习练者
                }
            if (Model.Ulevel == 2)
            {
                @:中级习练者
                }
            if (Model.Ulevel == 3)
            {
                @:高级习练者
                }


        }
    </p>


</div>
@using (Html.BeginForm("LevelAuthentication1", "YogaUserDetail", FormMethod.Post, new { id = "authform" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="lb_jbrz" style=" margin:0px; margin-left:32px">

        @Html.HiddenFor(model => model.ID)
        
        <div class="editor-field">
        </div>
        <div class="editor-label">
            1、 习练瑜伽的年限？ 
        </div>
        <div class="editor-field">
            @Html.RadioButtonFor(m => m.StartYear, 1, new { @id = "StartYear1", @name = "StartYear", @class = "lb_ridao" })<span class="lb_level_span">A、0-1年</span><br />
            @Html.RadioButtonFor(m => m.StartYear, 2, new { @id = "StartYear2", @name = "StartYear", @class = "lb_ridao" })<span class="lb_level_span">B、1-3年</span><br />
            @Html.RadioButtonFor(m => m.StartYear, 3, new { @id = "StartYear3", @name = "StartYear", @class = "lb_ridao" })<span class="lb_level_span">C、3-5年</span><br />
            @Html.RadioButtonFor(m => m.StartYear, 4, new { @id = "StartYear4", @name = "StartYear", @class = "lb_ridao" })<span class="lb_level_span">D、5年以上</span>
        </div>

        <div class="editor-label">
            2、练习瑜伽的频率 
        </div>
        <div class="editor-field">
            @Html.RadioButtonFor(m => m.IsUserWeeknumber, 1, new { @id = "IsUserWeeknumber1", @name = "IsUserWeeknumber", @class = "lb_ridao" })<span class="lb_level_span">A、每周2-3次瑜伽课程习练。</span><br />
            @Html.RadioButtonFor(m => m.IsUserWeeknumber, 2, new { @id = "IsUserWeeknumber2", @name = "IsUserWeeknumber", @class = "lb_ridao" })<span class="lb_level_span">B、每周4-5次瑜伽课程习练。</span><br />
            @Html.RadioButtonFor(m => m.IsUserWeeknumber, 3, new { @id = "IsUserWeeknumber3", @name = "IsUserWeeknumber", @class = "lb_ridao" })<span class="lb_level_span">C、每周有规律的瑜伽课程或自我习练。</span><br />
            @Html.RadioButtonFor(m => m.IsUserWeeknumber, 4, new { @id = "IsUserWeeknumber4", @name = "IsUserWeeknumber", @class = "lb_ridao" })<span class="lb_level_span">D、每日有规律的自我习练。</span>
        </div>

        <div class="editor-label">
            3、习练瑜伽的内容 
        </div>
        <div class="editor-field">
            @Html.RadioButtonFor(m => m.sContent, 1, new { @id = "sContent1", @name = "sContent", @class = "lb_ridao" })<span class="lb_level_span">A、有瑜伽导师带领的瑜伽体式习练。</span><br />
            @Html.RadioButtonFor(m => m.sContent, 2, new { @id = "sContent2", @name = "sContent", @class = "lb_ridao" })<span class="lb_level_span"> B、有导师带领瑜伽体式习练+瑜伽呼吸法。 </span>
            <br />
            @Html.RadioButtonFor(m => m.sContent, 3, new { @id = "sContent3", @name = "sContent", @class = "lb_ridao" })<span class="lb_level_span"> C、有导师带领体式习练+瑜伽呼吸控制法，并熟练掌握常用体式要领，基本的呼吸控制法、清洁法要领。</span><br />
            @Html.RadioButtonFor(m => m.sContent, 4, new { @id = "sContent4", @name = "sContent", @class = "lb_ridao" })<span class="lb_level_span">D、自我习练瑜伽体式+瑜伽呼吸控制法+清洁法+冥想。</span>

        </div>

        <div class="editor-label">
            4、瑜伽理论知识 
        </div>
        <div class="editor-field">
            @Html.RadioButtonFor(m => m.knowledge, 1, new { @id = "knowledge1", @name = "knowledge", @class = "lb_ridao" })<span class="lb_level_span">A、了解瑜伽基础知识、瑜伽呼吸知识要领。</span><br />
            @Html.RadioButtonFor(m => m.knowledge, 2, new { @id = "knowledge2", @name = "knowledge", @class = "lb_ridao" })<span class="lb_level_span">B、学习瑜伽知识，掌握瑜伽呼吸法知识要领、清洁法要领。</span><br />
            @Html.RadioButtonFor(m => m.knowledge, 3, new { @id = "knowledge3", @name = "knowledge", @class = "lb_ridao" })<span class="lb_level_span"> C、系统的学习瑜伽知识理论，掌握瑜伽呼吸控制法知识要领、清洁法要领、对冥想有一定的了解。</span><br />
            @Html.RadioButtonFor(m => m.knowledge, 4, new { @id = "knowledge4", @name = "knowledge", @class = "lb_ridao" })<span class="lb_level_span">D、深入了解瑜伽哲学，阅读瑜伽经典、掌握瑜伽呼吸控制法知识要领、清洁法要领、对冥想有深入研究。</span>

        </div>
        <div class="lb_save" style="width:600px;">

            <input type="button" id="btn_submit" value="提交" />
        </div>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () { 
            $("#btn_submit").click(function () {
                $.ajax({
                    type: "POST",
                    url: "/YogaUserDetail/LevelAuthentication1",
                    data: $("#authform").serialize(),
                    success: function (result) {
                        result=parseInt(result);
                        if (result >= 1) {
                            var level = "";
                            if (result == 1) {
                                level = "初级";
                            }
                            else if (result == 2) { 
                                level = "中级";
                            }
                            else if (result == 3) {
                                level = "高级";
                            }
                            else {
                                layer.alert("认证失败，", { icon: 6 });
                            }
                            layer.alert("恭喜您已达到" + level + "习练者级别！", {title:"认证成功"});
                        }
                        else if (result == 0) {
                            layer.alert("自评分数不足以升级，升级失败", { icon: 6 });
                        }
                        else {
                            layer.alert("级别异常，无法升级", { icon: 6 });
                        }
                    },
                    error: function (result) {
                        layer.alert("认证失败", { icon: 6 });
                    }
                });

            }); 
        });
    </script>
}