IYogaKoo/Controllers/YogisModelsController.cs
using Commons.Helper;
using IYogaKoo.Client;
using IYogaKoo.Entity;
using IYogaKoo.ViewModel;
using IYogaKoo.ViewModel.Commons.Enums;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using zzfIBM.WebControls.Mvc;

namespace IYogaKoo.Controllers
{
    public class YogisModelsController : Controller
    {

        //
        // GET: /YogisModels/

        ///获取用户信息cookie
        BasicInfo user = Commons.Helper.Login.GetCurrentUser();
        YogisModelsServiceClient client;
        YogaUserServiceClient clientUser;
        tMessageServiceClient clientMsg;
        FollowServiceClient clientFoll;
        YogaUserDetailServiceClient clientDetail;
        tWriteLogServiceClient logClient;
        YogaPictureServiceClient clientPic;
        YogaDicItemServiceClient dicclient;
        CentersServiceClient cenclient;
        LevelOrderServiceClient levelorderclient;
        /// <summary>
        /// 我感兴趣的活动
        /// </summary>
        InterestServiceClient interclient;
        /// <summary>
        /// 我报名的活动
        /// </summary>
        OrderServiceClient orderclient;
        ClassServiceClient classclient;
        method method;
        tZanModelsServiceClient zanclient;
        public YogisModelsController()
        {
            ViewBag.user = user;
            client = new YogisModelsServiceClient();
            clientUser = new YogaUserServiceClient();
            clientMsg = new tMessageServiceClient();
            clientFoll = new FollowServiceClient();
            clientDetail = new YogaUserDetailServiceClient();

            logClient = new tWriteLogServiceClient();
            clientPic = new YogaPictureServiceClient();
            dicclient = new YogaDicItemServiceClient();
            interclient = new InterestServiceClient();
            orderclient = new OrderServiceClient();
            classclient = new ClassServiceClient();
            method = new method();
            zanclient = new tZanModelsServiceClient();
            cenclient = new CentersServiceClient();
            levelorderclient = new LevelOrderServiceClient();
            #region 登录者的级别
            if (user.UserType == 0)
            {
                ViewYogaUserDetail temp = new ViewYogaUserDetail();
                temp = clientDetail.GetYogaUserDetailById(user.Uid);
                if (temp != null)
                    ViewBag.level = temp.Ulevel;
            }
            else
            {
                ViewYogisModels vyogism = new ViewYogisModels();
                vyogism = client.GetYogisModelsById(user.Uid);
                if (vyogism != null)
                    ViewBag.level = vyogism.YogisLevel;
            }
            #endregion
            #region  站内信-信息数量

            int tinstatcount = 0;
            int follcount = 0;
            int zancount = 0;
            int msgcount = 0;

            method.InstationInfo(user.Uid, out   tinstatcount, out   follcount, out   zancount, out   msgcount);

            ViewBag.tinstatcount = tinstatcount;
            ViewBag.follcount = follcount;
            ViewBag.zancount = zancount;
            ViewBag.msgcount = msgcount;
            ViewBag.AllCount = tinstatcount + follcount + zancount + msgcount;
            #endregion

        }

        public ActionResult Index(int page = 1)
        {
            //派别
            int typeid = 0;
            if (!string.IsNullOrEmpty(Request.Form["typeid"]))
            {
                typeid = Convert.ToInt32(Request.Form["typeid"]);
            }
            int level = 0;
            //瑜伽类别
            if (!string.IsNullOrEmpty(Request.Form["levelid"]))
            {
                level = Convert.ToInt32(Request.Form["levelid"]);
            }

            //国家
            int CountryID = 0;
            if (!string.IsNullOrEmpty(Request.Form["hidCountryID"]))
            {
                CountryID = Convert.ToInt32(Request.Form["hidCountryID"]);
            }

            //省份
            int ProvinceID = 0;
            if (!string.IsNullOrEmpty(Request.Form["hidProvinceID"]))
            {
                ProvinceID = Convert.ToInt32(Request.Form["hidProvinceID"]);
            }

            //城市
            int CityID = 0;
            if (!string.IsNullOrEmpty(Request.Form["hidCityID"]))
            {
                CityID = Convert.ToInt32(Request.Form["hidCityID"]);
            }
            //地区
            int DistrictID = 0;
            if (!string.IsNullOrEmpty(Request.Form["hidDistrictID"]))
            {
                DistrictID = Convert.ToInt32(Request.Form["hidDistrictID"]);
            }

            string name = string.Empty;

            List<ViewYogisModels> list = new List<ViewYogisModels>();
            int count = 0;
            int pagesize = 12;

            list = client.GetYogisModelsList("", DistrictID, CityID, ProvinceID, CountryID, typeid, level, 2, out count);

            List<ViewUserModelsGroup> users = new List<ViewUserModelsGroup>();
            ViewUserModelsGroup user = new ViewUserModelsGroup();
            ViewYogaDicItem dicitem = null;
            foreach (ViewYogisModels c in list)
            {
                c.DisplayImg = CommonInfo.GetDisplayImg(c.DisplayImg);
                user = new ViewUserModelsGroup();
                user.VmList = c;
                //派别
                string typename = string.Empty;
                if (c.YogaTypeid != null)
                {
                    string[] arrtypeid = c.YogaTypeid.Split(',');

                    for (int i = 0; i < arrtypeid.Length; i++)
                    {
                        if (!String.IsNullOrEmpty(arrtypeid[i]))
                        {
                            int result = 0;
                            if (Int32.TryParse(arrtypeid[i], out result))
                            {
                                int a = result;
                                dicitem = dicclient.GetYogaDicItemById(result);
                                if (dicitem != null)
                                {
                                    typename += dicitem.ItemName + ",";
                                }
                            }
                        }
                    }
                    if (!String.IsNullOrEmpty(typename))
                    {
                        typename = typename.Substring(0, typename.Length - 1);
                    }
                }
                user.usertype = typename;
                //昵称
                //ViewYogaUser u = clientUser.GetYogaUserById(c.UID);
                //user.VyList = u;

                //粉丝
                user.FollowCount = clientFoll.GetFollowByCount(c.UID);
                users.Add(user);
            }
            users = users.OrderByDescending(x => x.FollowCount).
                OrderByDescending(x => !string.IsNullOrEmpty(x.VmList.DisplayImg)).
                OrderByDescending(x => !string.IsNullOrEmpty(x.VmList.CoverImg)).
                OrderByDescending(x => !string.IsNullOrEmpty(x.VmList.YogisDepict)).Skip((page - 1) * pagesize).Take(pagesize).ToList();

            Webdiyer.WebControls.Mvc.PagedList<ViewUserModelsGroup> pagelist = new Webdiyer.WebControls.Mvc.PagedList<ViewUserModelsGroup>(users, page, pagesize, count);
            if (Request.IsAjaxRequest())
            {
                return PartialView("IndexList", pagelist);
            }
            return View(pagelist);

        }

        //
        // GET: /YogisModels/Details/5

        /// <summary>
        ///  瑜伽达人/导师 主页
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>        
        public ActionResult Details(int id, int page = 1)
        {
            try
            {
                ///Follow iType
                ViewBag.UserType = 1;

                ViewBag.id = id;
                int strUid = user.Uid;
                // int iLoginID = user.Uid;//登录用户ID
                ViewBag.iLoginID = user.Uid;

                #region 导师专页 基本信息

                ViewYogisModels temp = new ViewYogisModels();

                temp = client.GetYogisModelsById(id);

                ViewBag.listGroup = temp;

                ///昵称
                ViewBag.NickName = clientUser.GetYogaUserById(temp.UID).NickName;
                if (user.Uid == id)//自己
                {
                    ViewBag.Gender = 2;
                }
                else
                {
                    ViewBag.Gender = temp.Gender.Value;
                }
                strUid = temp.UID;
                ViewBag.strUid = temp.UID;
                ///位置
                string strCountryID = "";
                string strProvinceID = "";
                string strCityID = "";
                string strDistrictID = "";
                if (temp.CountryID != null && temp.CountryID != 0)
                {
                    strCountryID = GetItemName(temp.CountryID.Value) + "·";
                }
                if (temp.ProvinceID != null && temp.ProvinceID != 0)
                {
                    strProvinceID = GetItemName(temp.ProvinceID.Value) + "·";
                }
                if (temp.CityID != null && temp.CityID != 0)
                {
                    strCityID = GetItemName(temp.CityID.Value) + "·";
                }
                if (temp.DistrictID != null && temp.DistrictID != 0)
                {
                    strDistrictID = GetItemName(temp.DistrictID.Value);
                }

                ViewBag.AddRessName = strCountryID + strProvinceID + strCityID + strDistrictID;
                #endregion

                #region 流派 / 影响他的导师 / 所在会馆
                if (!string.IsNullOrEmpty(temp.YogaTypeid))
                {
                    string[] ids = temp.YogaTypeid.Split(',');
                    foreach (var i in ids)
                    {

IYogaKoo/Views/YogisModels/Index.cshtml
@using Webdiyer.WebControls.Mvc
@model Webdiyer.WebControls.Mvc.PagedList<IYogaKoo.ViewModel.ViewUserModelsGroup>
@{
    ViewBag.Title = "导师";
}
@using (Html.BeginForm("Index", "YogisModels", new { id = "" }, FormMethod.Post, new { id = "searchForm" }))
{
    <div class="lb_login_idnex_top" style="border-top:5px solid #65C3A5">
        <div class="lb_login_idnex_top_index">
            <b>您所在位置：</b><span style="font-weight:bold">瑜伽导师</span>
        </div>
    </div>
    <div id="anchorTag" class="lb_lb_School_zhuti">
        <b>@*瑜伽导师：*@ &nbsp;</b>
        <ul>
            <li tid="0" class="on">全部</li>
            <li tid="1">初级老师</li>
            <li tid="2">中级老师</li>
            <li tid="3">高级老师</li>
            <li tid="5">资深导师</li>
            <li tid="6">知名导师</li>
            <li tid="4">瑜伽大师</li>
        </ul>
        <input type="hidden" id="levelid" name="levelid" />
    </div>
    <div class="lb_lb_School_liupaii">
        <b>瑜伽流派：</b>
        <ul>
            <li tid="0" class="on">全部</li>
            <li tid="115">哈他</li>
            <li tid="118">艾扬格</li>
            <li tid="119">阿斯汤加</li>
            <li tid="101">流瑜伽</li>
            <li tid="120">阴瑜伽</li>
        </ul>
        <input type="hidden" id="typeid" name="typeid" />
    </div>
    <div class="lb_lb_School_diqu">
        <b class="b">所在地区：</b>
        <select id="ddlCountryID" name="ddlCountryID"></select>
        <input type="hidden" name="hidCountryID" id="hidCountryID" />
        <select id="ddlProvinceID" name="ddlProvinceID">
            <option value="0">请选择省份</option>
        </select>
        <input type="hidden" name="hidProvinceID" id="hidProvinceID" />
        <select id="ddlCityID" name="ddlCityID" >
            <option value="0">请选择城市</option>
        </select>
        <input type="hidden" name="hidCityID" id="hidCityID" />
        <select id="ddlDistrictID" name="ddlDistrictID" >
            <option value="0">请选择城区</option>
        </select>
        <input type="hidden" name="hidDistrictID" id="hidDistrictID" />
    </div>
} 
 

<div class="lb_School_index_index" style="width:1210px">
    <div class="lb_School_index_index_lln">
        <div style="display:block" id="Content">
            @Html.Partial("IndexList", Model)
        </div>
    </div>
</div>
@section styles
{
    <link type="text/css" href="/Content/Front/css/pagerstyles.css" rel="stylesheet" />

}
@section scripts {
    <script type="text/javascript">
        $(function () {
            $(".lb_lb_School_zhuti ul li").click(function () {
                var typeid = $(this).attr("tid");
                $("#levelid").val(typeid);
                $(this).addClass("on").siblings().removeClass("on");
                $("#searchForm").submit();
            });
            $(".lb_lb_School_liupaii ul li").click(function () {
                var typeid = $(this).attr("tid");
                $("#typeid").val(typeid);
                $(this).addClass("on").siblings().removeClass("on");
                $("#searchForm").submit();
            });

            $.ajax({
                url: '/Login/GetCountryInfo?t=' + Math.random(),
                type: 'post',
                datatype: 'json',
                success: function (data) {
                    $("#ddlCountryID").append("<option value='0' selected='selected'>请选择国家</option>");
                    for (var i = 0; i < data.length; i++) {
                        $("#ddlCountryID").append("<option value='" + data[i].ID + "'   >" + data[i].ItemName + "</option>");
                    };
                }
            });
           
        });

        // 国家事件
        $('#ddlCountryID').change(function () {
            var strGuoJia = $(this).val();
            $("#hidCountryID").val(strGuoJia);
            //加载省
            $.ajax({
                url: '/Login/GetAreaInfo?id=' + strGuoJia,
                type: 'post',
                datatype: 'json',
                success: function (data) {
                    $("#ddlProvinceID").html("<option value='0'>请选择</option>");
                    $("#ddlCityID").html("<option value='0'>请选择</option>");
                    $("#ddlDistrictID").html("<option value='0'>请选择</option>");
                    for (var i = 0; i < data.length; i++) {

                        $("#ddlProvinceID").append("<option value='" + data[i].ID + "'>" + data[i].ItemName + "</option>");

                    };
                }
            });
            $("#searchForm").submit();
        });
        //省事件
        $("#ddlProvinceID").change(function () {
            var strSheng = $(this).val();
            $("#hidProvinceID").val(strSheng);
            //加载市
            $.ajax({
                url: '/Login/GetAreaInfo?id=' + strSheng,
                type: 'post',
                datatype: 'json',
                success: function (data) {
                    $("#ddlCityID").html("<option value='0'>请选择</option>");
                    //$("#ddlDistrictID").html("<option value='0'>请选择</option>");
                    for (var i = 0; i < data.length; i++) {

                        $("#ddlCityID").append("<option value='" + data[i].ID + "'>" + data[i].ItemName + "</option>");

                    };
                }
            });
            $("#searchForm").submit();
        });
        //城市事件
        $("#ddlCityID").change(function () {
            var strShi = $(this).val();
            $("#hidCityID").val(strShi);
            //加载城区
            $.ajax({
                url: '/Login/GetAreaInfo?id=' + strShi,
                type: 'post',
                datatype: 'json',
                success: function (data) {
                   // $("#ddlDistrictID").append("<option value='0'>请选择</option>");
                    for (var i = 0; i < data.length; i++) {

                        $("#ddlDistrictID").append("<option value='" + data[i].ID + "'>" + data[i].ItemName + "</option>");

                    };
                }
            });
            $("#searchForm").submit();
        });
        //城市事件
        $("#ddlDistrictID").change(function () {
            var strShi = $(this).val(); console.log(strShi);
            $("#hidDistrictID").val(strShi);
            $("#searchForm").submit();
        });
        function pagelocation() { 
            $("html,body").stop(true); $("html,body").animate({ scrollTop: $("#anchorTag").offset().top }, 100);
        }
    </script>

    <script src=@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")></script>
    @{Html.RegisterMvcPagerScriptResource();}
}

IYogaKoo/Views/YogisModels/IndexList.cshtml
@using Webdiyer.WebControls.Mvc
@model Webdiyer.WebControls.Mvc.PagedList<IYogaKoo.ViewModel.ViewUserModelsGroup>
@{
    Layout = null;
}
 
@foreach (var item in Model)
{
    <div class="lb_teacher_div2">
        <div class="lb_teacher_div_top" style="text-align:center">
            @{
    string title = string.Empty;
    if (item.VmList != null && item.VmList.RealName != null)
    {
        title = item.VmList.RealName;
    }
            }
            @if (item.VmList.YogisLevel == 4)
            {
                <a href="/Yogaguru/Details/@item.VmList.UID"   title="@title">
                    <img src="@(!String.IsNullOrEmpty(item.VmList.DisplayImg) ? Commons.Helper.CommonInfo.GetDisplayImg(item.VmList.DisplayImg) : "/Content/Front/images/defaultImg.png")" onerror="javascript: this.src = '/Content/Front/images/defaultImg.png'" width="278"   height="230">
                </a>
            }
            else
            {
                <a href="/YogisModels/Details/@item.VmList.UID"  title="@title">
                    <img src="@(!String.IsNullOrEmpty(item.VmList.DisplayImg) ? Commons.Helper.CommonInfo.GetDisplayImg(item.VmList.DisplayImg) : "/Content/Front/images/defaultImg.png")" onerror="javascript: this.src = '/Content/Front/images/defaultImg.png'" width="278"  height="230">
                </a>
            }
        </div>
        <div class="lb_teacher_div_bottom">
            <div class="lb_teacher_div_bottom_top">
                <b>  @{
    if (item.VmList != null && item.VmList.RealName != null)
    {
        string temprealname = item.VmList.RealName.Replace("(", "（");
        int khindex = temprealname.IndexOf("（");
        if (khindex > 0)
        {           
    @(temprealname.Substring(0, khindex))
    <br/>
            int khindex2 = temprealname.Length - khindex;
                        
                    @(temprealname.Substring(temprealname.IndexOf("（") + 1, khindex2 - 2)) 
       }
        else
        {
            @temprealname
        }
    }

                }
                </b>
                <span style="float:right; margin-right:5px;">@item.FollowCount</span><a></a>
            </div>
            <div class="lb_teacher_div_bottom_top2">
                <p word="@item.VmList.GudWords">
                    @{
    if (item.VmList.GudWords != null)
    {
        if (item.VmList.GudWords.Length > 31)
        {
            @(item.VmList.GudWords.Substring(0, 31)+"..")
        }
        else
        {
            @item.VmList.GudWords
        }
    }
                    }


                </p>
            </div>
        </div>
    </div>
   
}
<script type="text/javascript">
    $(function () {
        //悬浮
        var xuindex;
        $(".lb_teacher_div_bottom_top2 p").hover(function () {
            var pval = $(this).attr("word");
            xuindex = layer.tips(pval, this, { tips: [1, '#65c3a5'] }); console.log(index);
        }, function () {
            layer.close(xuindex);
        });
    });
</script>
<div style="clear:both"></div>
<div style="display:block; width:100%">
    <div class="text-center" style="" id="menepager">
        @Ajax.Pager(Model, new PagerOptions
{
    PageIndexParameterName = "page",
    PrevPageText = "上一页",
    NextPageText = "下一页",
    FirstPageText = "首页",
    LastPageText = "尾页",  
    ContainerTagName = "ul",
    CssClass = "menepager",
    CurrentPagerItemTemplate = "<li class=\"active\"><a >{0}</a></li>",
    DisabledPagerItemTemplate = "<li class=\"disabled\"><a>{0}</a></li>",
    PagerItemTemplate = "<li>{0}</li>"
}, new MvcAjaxOptions { UpdateTargetId = "Content", HttpMethod = "Post", DataFormId = "searchForm", OnComplete = "pagelocation" })
    </div>
</div>

IYogaKoo/Views/YogisModels/LevelAuthentication.cshtml
@model IYogaKoo.ViewModel.ViewYogisModels

@{
    ViewBag.Title = "LevelAuthentication";
    Layout = "~/Views/Shared/_LayoutSetUp.cshtml";
}

<h2>级别认证</h2>

@using (Html.BeginForm("LevelAuthentication","YogisModels",FormMethod.Post, new { id = "authform" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>

        @Html.HiddenFor(model => model.YID)
       
        <div>
            <a href="/YogisModels/Audit">升级导师</a>（如进行导师级别晋升认证，请完成下列自评）
        </div><br />
        <div>

        </div>
        <div class="editor-label"  id="lb_casuhs">
            @Html.LabelFor(model => model.YogisLevel)：
            @{
    if (Model.YogisLevel == null || Model.YogisLevel == 0)
    {
        @:未设置
    }
    else
    {
        if (Model.YogisLevel == 1)
        {
            @:初级
        }
        if (Model.YogisLevel == 2)
        {
            @:中级
        }
        if (Model.YogisLevel == 3)
        {
            @:高级
        }
        if (Model.YogisLevel == 4)
        {
            @:大师
        }
    }

            }
        </div>
        <br/>
        <br />
        <div class="editor-label">
            级别晋升自评
            </div>
            <div class="editor-field">

            </div>
            <div class="editor-label">
                1、 习练瑜伽的年限？
            </div>
            <div class="editor-field">
                <input type="radio" name="yearNums" value="1" class="lb_ridao" /><span class="lb_level_span">A、1-3年</span><br /><br />
                <input type="radio" name="yearNums" value="2" class="lb_ridao" /><span class="lb_level_span">B、3-5年</span><br /><br />
                <input type="radio" name="yearNums" value="3" class="lb_ridao" /><span class="lb_level_span">C、5-10年</span><br /><br />
                <input type="radio" name="yearNums" value="4" class="lb_ridao" /><span class="lb_level_span">D、10年以上</span>
            </div>

            <div class="editor-label">
                2、参加瑜伽教学资格的培训？
            </div>
            <div class="editor-field">
                <input type="radio" name="yogaPinl" value="1" class="lb_ridao" /><span class="lb_level_span">A、正规学院200小时导师认证培训</span><br /><br />
                <input type="radio" name="yogaPinl" value="2" class="lb_ridao" /><span class="lb_level_span">B、正规学院中级导师认证培训</span><br /><br />
                <input type="radio" name="yogaPinl" value="3" class="lb_ridao" /><span class="lb_level_span">C、正规学院高级导师认证培训</span><br /><br />
                <input type="radio" name="yogaPinl" value="4" class="lb_ridao" /><span class="lb_level_span">D、参加不同流派多级认证培训</span>
            </div>
            <div class="editor-label">
                3、教授的年限
            </div>
            <div class="editor-field">
                <input type="radio" name="JiaoNums" value="1" class="lb_ridao" /><span class="lb_level_span">A、0-1年</span><br /><br />
                <input type="radio" name="JiaoNums" value="2" class="lb_ridao" /><span class="lb_level_span">B、1-3年</span><br /><br />
                <input type="radio" name="JiaoNums" value="3" class="lb_ridao" /><span class="lb_level_span">C、3-5年</span><br /><br />
                <input type="radio" name="JiaoNums" value="4" class="lb_ridao" /><span class="lb_level_span">D、5年以上</span>
            </div>
            <div class="editor-label">
                4、自我习练瑜伽的频率
            </div>
            <div class="editor-field">
                <input type="radio" name="yogaUserPl" value="1" class="lb_ridao" /><span class="lb_level_span">A、有规律自我习练</span><br /><br />
                <input type="radio" name="yogaUserPl" value="2" class="lb_ridao" /><span class="lb_level_span">B、每周至少3天瑜伽课程习练 </span> <br /><br />
                <input type="radio" name="yogaUserPl" value="3" class="lb_ridao" /><span class="lb_level_span">C、每周至少进行5天自我习练</span><br /><br />
                <input type="radio" name="yogaUserPl" value="4" class="lb_ridao" /><span class="lb_level_span">D、持续不间断的坚持每日自我习练</span>

            </div>
            <div class="editor-label">
                5、习练瑜伽的内容
            </div>
            <div class="editor-field">
                <input type="radio" name="yogaContent" value="1" class="lb_ridao" /><span class="lb_level_span">A、教授基础瑜伽体式、基本呼吸方法及练习要领</span><br /><br />
                <input type="radio" name="yogaContent" value="2" class="lb_ridao" /><span class="lb_level_span">B、教授常用的瑜伽体式习练+基本的瑜伽呼吸控制法，冥想课程、基础的清洁法要领</span> <br /><br />
                <input type="radio" name="yogaContent" value="3" class="lb_ridao" /><span class="lb_level_span">C、教授常用的瑜伽中级体式习练+常用的瑜伽呼吸控制法，冥想课程、基础的清洁法要领</span><br /><br />
                <input type="radio" name="yogaContent" value="4" class="lb_ridao" /><span class="lb_level_span">D、教授瑜伽高级体式+常用的瑜伽呼吸控制法+清洁法+冥想课程等瑜伽相关的所有课程和内容；并可以独立开设专题工作坊课程</span>

            </div>

            <div class="editor-label">
                6、瑜伽理论知识
            </div>
            <div class="editor-field" style="float:none">
                <input type="radio" name="yogaknowledge" value="1" class="lb_ridao" /><span class="lb_level_span">A、了解瑜伽基础知识、瑜伽呼吸知识要领。</span><br /><br />
                <input type="radio" name="yogaknowledge" value="2" class="lb_ridao" /><span class="lb_level_span">B、学习瑜伽知识，掌握瑜伽呼吸法知识要领、清洁法要领。</span><br /><br />
                <input type="radio" name="yogaknowledge" value="3" class="lb_ridao" /><span class="lb_level_span">C、系统的学习瑜伽知识理论，掌握瑜伽呼吸控制法知识要领、清洁法要领、对冥想有一定的了解。</span><br /><br />
                <input type="radio" name="yogaknowledge" value="4" class="lb_ridao" /><span class="lb_level_span">D、深入了解瑜伽哲学，阅读瑜伽经典、掌握瑜伽呼吸控制法知识要领、清洁法要领、对冥想有深入研究。</span>

            </div>
            <div class="lb_save" style="float:none; width:600px">
                <input type="button" id="btn_submit" value="提交" />
            </div>
</fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () { 
            $("#btn_submit").click(function () {
                $.ajax({
                    type: "POST",
                    url: "/YogisModels/LevelAuthentication",
                    data: $("#authform").serialize(),
                    success: function (result) {
                        if (result >= 1)
                        {
                            var level = "";
                            if (result == 1) {
                                level = "初级";
                            }
                            else if (result == 2) {
                                level = "中级";
                            }
                            else if (result == 3) {
                                level = "高级";
                            }
                            else {
                                layer.alert("升级失败，", { icon: 6 });
                            }
                            UpgradeEvent(level);
                        }
                        else if (result == 0) {
                            layer.alert("自评分数不足以升级，升级失败", { icon: 6 });
                        }
                        else {
                            layer.alert("级别异常，无法升级", { icon: 6 });
                        }
                        
                    },
                    error: function (result) {
                        layer.alert("提交失败",{icon:6});
                    }
                });

            });
           // UpgradeEvent("大师");
        });
        function UpgradeEvent(dslevel)
        {
            layer.confirm("您好！根据您的自评选项，综合评测，你现已达到" + dslevel + "导师级别。请您选择是否上传资质证明，进一步完成级别的认证。", {
                btn: ["提交", "完成"],title:"提示",icon:3
            }, function () {
                //资质认证界面               
                location.href = "/YogisModels/AuditEdit";
            }, function () {
                //完成
                UpgradeEvent2();
            });
        }
        function UpgradeEvent2() {
            layer.confirm("如果不进行一下步提交上传资料，直接完成您的级别状态将不会晋升，是否继续？", {
                btn: ["继续提交", "完成"], title: "提示", icon: 3
            }, function () {
                //资质认证界面
                location.href = "/YogisModels/AuditEdit";
            });
        }
    </script>
}